repos:
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.1
    hooks:
    - id: pylint
      args:
      - -d import-error
      - -d duplicate-code
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
